### ISSUE TITLE
HTTPError: Signing request failed: 400 Bad Request

### ISSUE THREAD

**Issue by k-sakoda** [castlabs/electron-releases#82]
Using electron-builder, I got `HTTPError` .

Here is the afterPack script I am using:
```
const util = require('util')
const childProcess = require('child_process')
const exec = util.promisify(childProcess.exec)

async function evsProcess(appPath) {
  const res = await exec('python3 -m castlabs_evs.vmp sign-pkg --persistent ' + appPath)
  console.log(res.stdout)
}
await evsProcess(context.appOutDir).catch(e => console.log(e))
```

stdout is:
```
'Signing: /Users/XXXXX/path/to/project/dist_electron/win-ia32-unpacked/XXXXX.exe\n' +
    ' - Verifying existing VMP signature\n' +
    ' - Signature invalid: Certificate is valid for development only\n' +
    ' - Requesting VMP signature\n' +
    'HTTPError: Signing request failed: 400 Bad Request\n' +
    ' <- InvalidDataError: Failed to generate verification digest\n' +
    " <- NameError: name 'HASH_BLOCK' is not defined\n",
```

Curiously, building for macOS doesn't cause any problems, and building for Windows gives this error.

**Comment by kokarare1212** [comment]
I received a similar message.
```
C:\Users\***\Downloads\electron-v10.1.7-win32-x64>py -m castlabs_evs.vmp sign-pkg -p -f .
Signing: .\electron.exe
 - Requesting VMP signature
HTTPError: Signing request failed: 400 Bad Request
 <- InvalidDataError: Failed to generate verification digest
 <- NameError: name 'HASH_BLOCK' is not defined

C:\Users\***\Downloads\electron-v10.1.7-win32-x64>
```

**Comment by khwaaj** [comment]
Yes, there was a service update a few hours ago that apparently introduced this issue with signing Windows builds. It has been fixed now, so everything should be back to normal. I apologize for any inconvenience, and thank you for reporting it!

FYI, there was also a new release candidate of the EVS client published. Among other things, this version adds caching to speed up cases where the same build is signed repeatedly, so I'd suggest you update to benefit from that, (e.g. by doing `python3 -m pip install --upgrade castlabs-evs`).

**Comment by kokarare1212** [comment]
Sorry.
I tried after updating castlabs-evs to version 1.0.0rc3, but I still can't sign with the above status.
```
C:\Users\***\Downloads\electron-v10.1.7-win32-x64>py -m castlabs_evs.vmp sign-pkg .
Signing: .\electron.exe
 - Verifying existing VMP signature
 - Signature invalid: Failed to read signature
 - Requesting VMP signature
HTTPError: Signing request failed: 400 Bad Request
 <- ValidityError: Binary signature denied
```

**Comment by khwaaj** [comment]
This is the message you get if you try to sign an unauthorized binary image, i.e. something that is not one off our ECS releases. I can see the binary you are trying to sign has no pre-existing signature like our releases do, are you perhaps trying to sign a stock Electron release?

If so, the corresponding release of ECS is available [here](https://github.com/castlabs/electron-releases/releases/tag/v10.1.7-wvvmp).

**Comment by PhantomNimbi** [comment]
I'm getting this on Windows as well now:

```yml
(C:\NativeAppsCompiler\tmp\env) C:\NativeAppsCompiler\bin>python -m castlabs_evs.vmp sign-pkg --persistent "%userprofile%\AppData\Local\Native Apps\apps\Netflix\netflix-win32-x64"
Signing: C:\Users\Joshu\AppData\Local\Native Apps\apps\Netflix\netflix-win32-x64\netflix.exe
 - Verifying existing VMP signature
 - Signature invalid: Failed to read signature
 - Requesting VMP signature
HTTPError: Signing request failed: 400 Bad Request
 <- ValidityError: Binary signature denied
```

**Python Version**: `Python 3.9.6`
**pip Version**: `pip 21.2.3 from C:\NativeAppsCompiler\tmp\env\lib\site-packages\pip (python 3.9)`
**Castlabs_EVS Version**:  `vmp.py 1.0.0`
**OS**: `Windows 11 Pro`
